# Project Euler Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:
#
#	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.
# 
# Link : https://projecteuler.net/problem=2
#

#the last number
n = 4000000

def get_even_fibonacci(n):
	#counters
	a = 1
	b = 1
	sum = 0 

	while( a <= n ):
		if (a%2 == 0):
			sum+=a
		temp = a
		a = a+b
		b = temp
	return sum

print get_even_fibonacci(n)
